Implementation;Generate Bitstream;RootName:zjh_CE2
Implementation;Compile;RootName:zjh_CE4
Implementation;Compile||(null)||Please refer to the log file for details about 1 Warning(s) , 1 Info(s)||zjh_CE4_compile_log.rpt;liberoaction://open_report/file/zjh_CE4_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:zjh_CE4
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||zjh_CE4_placeroute_log.rpt;liberoaction://open_report/file/zjh_CE4_placeroute_log.rpt||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
